stages:
  split_data:
    cmd: python src\data\split.py
    deps:
    - data\raw_data\raw.csv
    - src\data\split.py
    outs:
    - data\processed\X_test.csv
    - data\processed\X_train.csv
    - data\processed\y_test.csv
    - data\processed\y_train.csv
  normalize_data:
    cmd: python src\data\normalisation.py
    deps:
    - data\processed\X_test.csv
    - data\processed\X_train.csv
    - src\data\normalisation.py
    outs:
    - data\processed\X_test_scaled.csv
    - data\processed\X_train_scaled.csv
  grid_search:
    cmd: python src\models\GridSearch.py
    deps:
    - data\processed\X_train_scaled.csv
    - data\processed\y_train.csv
    - src\models\GridSearch.py
    outs:
    - models\best_params.pkl
  train_model:
    cmd: python src\models\train.py
    deps:
    - data\processed\X_train_scaled.csv
    - data\processed\y_train.csv
    - models\best_params.pkl
    - src\models\train.py
    outs:
    - models\trained_model.pkl
  evaluate_model:
    cmd: python src\models\evaluate.py
    deps:
    - data\processed\X_test_scaled.csv
    - data\processed\y_test.csv
    - models\trained_model.pkl
    - src\models\evaluate.py
    outs:
    - data\predictions\predictions.csv
    - metrics\scores.json
